version: "3.8"
services:
  # ui-service
  ui-service:
    build:
      context: ./ui-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REVERT_SERVICE_PORT=5001
      - TO_UPPER_SERVICE_PORT=5002
      - TO_LOWER_SERVICE_PORT=5003
    depends_on:
      - text-revert-service
      - text-to_upper-service
      - text-to_lower-service

  # text-revert-service
  text-revert-service:
    build:
      context: ./text-revert-service
    ports:
      - "5001:5001"
    environment:
      PORT: 5001

  # text-to_upper-service
  text-to_upper-service:
    build:
      context: ./text-to_upper-service
    ports:
      - "5002:5002"
    environment:
      PORT: 5002

  # text-to_lower-service
  text-to_lower-service:
    build:
      context: ./text-to_lower-service
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
  # redis
  redis:
    image: "redis:alpine"